# Default values for namespace-default.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "<your namespace name>"

ecrJob:
  baseName: ecr   # change if you want multiple ecr cronjobs in same namespace
  enabled: true   # set to false if you do not want to deploy the ECR job
  schedule: "0 */11 * * *"   # every 11 hours, for every 5 min use */5 * * * *
  awsAccount: "347728829864"   # Replace with your AWS account ID
  awsRegion: "eu-central-1"   # Replace with your ECR region
  awsCredentialSecret: "aws-credentials"   # secret storing AWS credentials
  ecrRegistrySecret: ecr-pull-secret   # ECR token secret name
  toolImage: "ghcr.io/pflege-de/awscli-kubectl:v1.2"
  toolImageRegistrySecret: "ghcr-pull-secret"   # name a secret for toolImage
  dualRegistrySecret:
    enabled: false   # enable to store credentials of ECR and other registry
    registrySecret: "" # secret that will be combined with the ECR secret
    dualSecretName: "dual-registry-secret" # name of the new secret

gitJob:
  enabled: false   # set to true in case you want the git rebuilder cronjob
  schedule: "0 0 * * *"   # Run every day at midnight
  githubSshSecret: "github-ssh-secret"   # secret of AWS login credentials
  repoUrl: "undefined"
  branch: "undefined"

resourceQuota:   # limit for aggregate resource consumption in namespace
  enabled: false   # set to true in case you want to deploy quota
  requestsCpu: "250m"
  requestsMemory: "512Mi"
  limitsCpu: "500m"
  limitsMemory: "1Gi"

limitRange:   # limits for individual objects within namespace
  enabled: false   # set to true in case you want to deploy the limit range
  maxCpu: "500m"
  maxMemory: 1Gi
  minCpu: "1m"
  minMemory: 1Mi
