{{- if .Values.ecrJob.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ecrJob.baseName }}-registry-helper-cm
  namespace: {{ .Values.namespace  }}
data:
  AWS_ACCOUNT: "{{ .Values.ecrJob.awsAccount }}" 
  AWS_REGION: "{{ .Values.ecrJob.awsRegion }}" 
  REGISTRY_SECRET: "{{ .Values.ecrJob.ecrRegistrySecret }}" # Replace with your desired ECR token secret name
  NAMESPACE_NAME: "{{ .Values.namespace  }}"
  CREATE_DUAL_REGISTRY_SECRET: "{{ .Values.ecrJob.dualRegistrySecret.enabled }}"
  DUAL_REGISTRY_SECRET: "{{ .Values.ecrJob.dualRegistrySecret.dualSecretName }}"
  SECOND_REGISTRY_SECRET: "{{ .Values.ecrJob.dualRegistrySecret.registrySecret }}"
  
{{- end }}

