apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}-limit-range
spec:
  limits:
    - type: Container
      max:
        cpu: "{{ .Values.limitRange.maxCpu }}"
        memory: {{ .Values.limitRange.maxMemory }}
      min:
        cpu: "{{ .Values.limitRange.minCpu }}"
        memory: {{ .Values.limitRange.minMemory }}