{{- if .Values.gitJob.enabled -}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.namespace  }}-git-rebuilder
  namespace: {{ .Values.namespace  }}
spec:
  schedule: "{{ .Values.gitJob.schedule }}"  # Run every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: ssh-key-volume
            secret:
              secretName: {{ .Values.gitJob.githubSshSecret }}
          containers:
          - name: {{ .Values.namespace  }}-git-rebuilder
            image: alpine/git
            command: ["/bin/sh", "-e", "-c"]
            resources:
              limits:
                cpu: 100m
                memory: 250Mi
              requests:
                cpu: 100m
                memory: 250Mi
            envFrom:
              - configMapRef:
                  name: {{ .Values.namespace  }}-git-rebuilder-cm 
            args:
            - |
              echo "setting user.email"
              git config --global user.email "autobuilder@pflege.de"
              git config --global user.name "autobuilder"
              echo "creating ssh key"
              mkdir ~/.ssh && chmod 600 ~/.ssh && cp /tmp/ssh-key/ssh-privatekey ~/.ssh/key && chmod 600 ~/.ssh/key
              export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/key"
              git clone --single-branch --branch $BRANCH $REPO_URL repo
              cd repo
              git commit --allow-empty -m "scheduled empty-commit to trigger build pipeline"
              git push origin $BRANCH
            volumeMounts:
            - name: ssh-key-volume
              mountPath: /tmp/ssh-key
          restartPolicy: Never
  successfulJobsHistoryLimit: 3  # Keep a maximum of 3 successful job history
  failedJobsHistoryLimit: 1      # Keep a maximum of 1 failed job history

{{- end }}