{{- if .Values.resourceQuota.enabled -}}

apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}-resource-quota
spec:
  hard:
    requests.cpu: "{{ .Values.resourceQuota.requestsCpu }}"
    requests.memory: {{ .Values.resourceQuota.requestsMemory }}
    limits.cpu: "{{ .Values.resourceQuota.limitsCpu }}"
    limits.memory: {{ .Values.resourceQuota.limitsMemory }}

{{- end }}