{{- if .Values.ecrJob.enabled -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ecr
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-full-access-to-ecr-secrets
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.ecrJob.ecrRegistrySecret }}"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-{{ .Values.ecrJob.baseName }}-secret-access
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sa-{{ .Values.ecrJob.baseName }} 
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-{{ .Values.ecrJob.baseName }}-secrets
  apiGroup: ""

{{- end }}