{{- if .Values.ecrJob.enabled -}}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-{{ .Values.ecrJob.baseName }}-secret-access
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sa-{{ .Values.ecrJob.baseName }} 
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-{{ .Values.ecrJob.baseName }}-secrets
  apiGroup: ""

{{- end }}