{{- if .Values.ecrJob.enabled -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-full-access-to-{{ .Values.ecrJob.baseName }}-secrets
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ .Values.ecrJob.ecrRegistrySecret }}"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]

{{- end }}